// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO user_credentials (user_id, password_hash) VALUES ($1, $2)
`

type CreateCredentialParams struct {
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.UserID, arg.PasswordHash)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token, ip_address, user_agent, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	IpAddress *string            `db:"ip_address" json:"ip_address"`
	UserAgent *string            `db:"user_agent" json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, avatar_url, google_sub, email_verified)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, avatar_url, bio, level, xp, visibility, google_sub, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	Email         *string `db:"email" json:"email"`
	Name          string  `db:"name" json:"name"`
	AvatarUrl     *string `db:"avatar_url" json:"avatar_url"`
	GoogleSub     *string `db:"google_sub" json:"google_sub"`
	EmailVerified bool    `db:"email_verified" json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.GoogleSub,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Level,
		&i.Xp,
		&i.Visibility,
		&i.GoogleSub,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT password_hash FROM user_credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, token, ip_address, user_agent, expires_at, created_at FROM sessions WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, avatar_url, bio, level, xp, visibility, google_sub, email_verified, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Level,
		&i.Xp,
		&i.Visibility,
		&i.GoogleSub,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, name, avatar_url, bio, level, xp, visibility, google_sub, email_verified, created_at, updated_at FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Level,
		&i.Xp,
		&i.Visibility,
		&i.GoogleSub,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, avatar_url, bio, level, xp, visibility, google_sub, email_verified, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Level,
		&i.Xp,
		&i.Visibility,
		&i.GoogleSub,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name       = COALESCE($2, name),
    avatar_url = COALESCE($3, avatar_url),
    bio        = COALESCE($4, bio),
    visibility = COALESCE($5, visibility),
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, name, avatar_url, bio, level, xp, visibility, google_sub, email_verified, created_at, updated_at
`

type UpdateUserParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	Name       *string   `db:"name" json:"name"`
	AvatarUrl  *string   `db:"avatar_url" json:"avatar_url"`
	Bio        *string   `db:"bio" json:"bio"`
	Visibility *string   `db:"visibility" json:"visibility"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.AvatarUrl,
		arg.Bio,
		arg.Visibility,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Level,
		&i.Xp,
		&i.Visibility,
		&i.GoogleSub,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGoogleUser = `-- name: UpsertGoogleUser :one
INSERT INTO users (google_sub, email, name, avatar_url, email_verified)
VALUES ($1, $2, $3, $4, TRUE)
ON CONFLICT (google_sub) DO UPDATE SET
    email      = EXCLUDED.email,
    name       = COALESCE(NULLIF(users.name, ''), EXCLUDED.name),
    avatar_url = COALESCE(users.avatar_url, EXCLUDED.avatar_url),
    updated_at = NOW()
RETURNING id, email, name, avatar_url, bio, level, xp, visibility, google_sub, email_verified, created_at, updated_at
`

type UpsertGoogleUserParams struct {
	GoogleSub *string `db:"google_sub" json:"google_sub"`
	Email     *string `db:"email" json:"email"`
	Name      string  `db:"name" json:"name"`
	AvatarUrl *string `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertGoogleUser,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Bio,
		&i.Level,
		&i.Xp,
		&i.Visibility,
		&i.GoogleSub,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
