// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bible.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bible_bookmarks (user_id, translation_id, book, chapter, verse)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, translation_id, book, chapter, verse) DO NOTHING
RETURNING id, user_id, translation_id, book, chapter, verse, created_at
`

type CreateBookmarkParams struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	TranslationID int64     `db:"translation_id" json:"translation_id"`
	Book          string    `db:"book" json:"book"`
	Chapter       int32     `db:"chapter" json:"chapter"`
	Verse         int32     `db:"verse" json:"verse"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (BibleBookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark,
		arg.UserID,
		arg.TranslationID,
		arg.Book,
		arg.Chapter,
		arg.Verse,
	)
	var i BibleBookmark
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TranslationID,
		&i.Book,
		&i.Chapter,
		&i.Verse,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bible_bookmarks WHERE id = $1 AND user_id = $2
`

type DeleteBookmarkParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.Exec(ctx, deleteBookmark, arg.ID, arg.UserID)
	return err
}

const deleteHighlight = `-- name: DeleteHighlight :exec
DELETE FROM bible_highlights WHERE id = $1 AND user_id = $2
`

type DeleteHighlightParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) error {
	_, err := q.db.Exec(ctx, deleteHighlight, arg.ID, arg.UserID)
	return err
}

const getBookmarks = `-- name: GetBookmarks :many
SELECT id, user_id, translation_id, book, chapter, verse, created_at FROM bible_bookmarks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetBookmarks(ctx context.Context, userID uuid.UUID) ([]BibleBookmark, error) {
	rows, err := q.db.Query(ctx, getBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibleBookmark{}
	for rows.Next() {
		var i BibleBookmark
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TranslationID,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChapter = `-- name: GetChapter :many
SELECT verse, text
FROM bible_verses
WHERE translation_id = $1 AND book = $2 AND chapter = $3
ORDER BY verse
`

type GetChapterParams struct {
	TranslationID int64  `db:"translation_id" json:"translation_id"`
	Book          string `db:"book" json:"book"`
	Chapter       int32  `db:"chapter" json:"chapter"`
}

type GetChapterRow struct {
	Verse int32  `db:"verse" json:"verse"`
	Text  string `db:"text" json:"text"`
}

func (q *Queries) GetChapter(ctx context.Context, arg GetChapterParams) ([]GetChapterRow, error) {
	rows, err := q.db.Query(ctx, getChapter, arg.TranslationID, arg.Book, arg.Chapter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChapterRow{}
	for rows.Next() {
		var i GetChapterRow
		if err := rows.Scan(&i.Verse, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyVerse = `-- name: GetDailyVerse :one
SELECT bv.book, bv.chapter, bv.verse, bv.text, bt.code AS translation_code
FROM bible_daily_cache dc
JOIN bible_verses bv ON bv.translation_id = dc.translation_id
    AND bv.book = dc.book AND bv.chapter = dc.chapter AND bv.verse = dc.verse
JOIN bible_translations bt ON bt.id = dc.translation_id
WHERE dc.cache_date = $1 AND dc.translation_id = $2
`

type GetDailyVerseParams struct {
	CacheDate     pgtype.Date `db:"cache_date" json:"cache_date"`
	TranslationID int64       `db:"translation_id" json:"translation_id"`
}

type GetDailyVerseRow struct {
	Book            string `db:"book" json:"book"`
	Chapter         int32  `db:"chapter" json:"chapter"`
	Verse           int32  `db:"verse" json:"verse"`
	Text            string `db:"text" json:"text"`
	TranslationCode string `db:"translation_code" json:"translation_code"`
}

func (q *Queries) GetDailyVerse(ctx context.Context, arg GetDailyVerseParams) (GetDailyVerseRow, error) {
	row := q.db.QueryRow(ctx, getDailyVerse, arg.CacheDate, arg.TranslationID)
	var i GetDailyVerseRow
	err := row.Scan(
		&i.Book,
		&i.Chapter,
		&i.Verse,
		&i.Text,
		&i.TranslationCode,
	)
	return i, err
}

const getHighlights = `-- name: GetHighlights :many
SELECT id, user_id, translation_id, book, chapter, verse, color, note, created_at FROM bible_highlights WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetHighlights(ctx context.Context, userID uuid.UUID) ([]BibleHighlight, error) {
	rows, err := q.db.Query(ctx, getHighlights, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibleHighlight{}
	for rows.Next() {
		var i BibleHighlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TranslationID,
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Color,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingProgress = `-- name: GetReadingProgress :many
SELECT user_id, translation_id, book, chapter, last_read_at FROM reading_progress WHERE user_id = $1 ORDER BY last_read_at DESC
`

func (q *Queries) GetReadingProgress(ctx context.Context, userID uuid.UUID) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, getReadingProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.UserID,
			&i.TranslationID,
			&i.Book,
			&i.Chapter,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranslationByCode = `-- name: GetTranslationByCode :one
SELECT id, code, short_name, name, language, created_at FROM bible_translations WHERE code = $1
`

func (q *Queries) GetTranslationByCode(ctx context.Context, code string) (BibleTranslation, error) {
	row := q.db.QueryRow(ctx, getTranslationByCode, code)
	var i BibleTranslation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShortName,
		&i.Name,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const getTranslations = `-- name: GetTranslations :many
SELECT id, code, short_name, name, language, created_at FROM bible_translations ORDER BY language, name
`

func (q *Queries) GetTranslations(ctx context.Context) ([]BibleTranslation, error) {
	rows, err := q.db.Query(ctx, getTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BibleTranslation{}
	for rows.Next() {
		var i BibleTranslation
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ShortName,
			&i.Name,
			&i.Language,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVerses = `-- name: SearchVerses :many
SELECT bv.book, bv.chapter, bv.verse, bv.text, bt.code AS translation_code
FROM bible_verses bv
JOIN bible_translations bt ON bt.id = bv.translation_id
WHERE bv.translation_id = $1 AND bv.text ILIKE '%' || $2 || '%'
ORDER BY bv.book, bv.chapter, bv.verse
LIMIT 50
`

type SearchVersesParams struct {
	TranslationID int64   `db:"translation_id" json:"translation_id"`
	Column2       *string `db:"column_2" json:"column_2"`
}

type SearchVersesRow struct {
	Book            string `db:"book" json:"book"`
	Chapter         int32  `db:"chapter" json:"chapter"`
	Verse           int32  `db:"verse" json:"verse"`
	Text            string `db:"text" json:"text"`
	TranslationCode string `db:"translation_code" json:"translation_code"`
}

func (q *Queries) SearchVerses(ctx context.Context, arg SearchVersesParams) ([]SearchVersesRow, error) {
	rows, err := q.db.Query(ctx, searchVerses, arg.TranslationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVersesRow{}
	for rows.Next() {
		var i SearchVersesRow
		if err := rows.Scan(
			&i.Book,
			&i.Chapter,
			&i.Verse,
			&i.Text,
			&i.TranslationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyVerse = `-- name: UpsertDailyVerse :exec
INSERT INTO bible_daily_cache (cache_date, translation_id, book, chapter, verse)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (cache_date, translation_id) DO UPDATE SET
    book    = EXCLUDED.book,
    chapter = EXCLUDED.chapter,
    verse   = EXCLUDED.verse
`

type UpsertDailyVerseParams struct {
	CacheDate     pgtype.Date `db:"cache_date" json:"cache_date"`
	TranslationID int64       `db:"translation_id" json:"translation_id"`
	Book          string      `db:"book" json:"book"`
	Chapter       int32       `db:"chapter" json:"chapter"`
	Verse         int32       `db:"verse" json:"verse"`
}

func (q *Queries) UpsertDailyVerse(ctx context.Context, arg UpsertDailyVerseParams) error {
	_, err := q.db.Exec(ctx, upsertDailyVerse,
		arg.CacheDate,
		arg.TranslationID,
		arg.Book,
		arg.Chapter,
		arg.Verse,
	)
	return err
}

const upsertHighlight = `-- name: UpsertHighlight :one
INSERT INTO bible_highlights (user_id, translation_id, book, chapter, verse, color, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, translation_id, book, chapter, verse) DO UPDATE SET
    color = EXCLUDED.color,
    note  = EXCLUDED.note
RETURNING id, user_id, translation_id, book, chapter, verse, color, note, created_at
`

type UpsertHighlightParams struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	TranslationID int64     `db:"translation_id" json:"translation_id"`
	Book          string    `db:"book" json:"book"`
	Chapter       int32     `db:"chapter" json:"chapter"`
	Verse         int32     `db:"verse" json:"verse"`
	Color         string    `db:"color" json:"color"`
	Note          *string   `db:"note" json:"note"`
}

func (q *Queries) UpsertHighlight(ctx context.Context, arg UpsertHighlightParams) (BibleHighlight, error) {
	row := q.db.QueryRow(ctx, upsertHighlight,
		arg.UserID,
		arg.TranslationID,
		arg.Book,
		arg.Chapter,
		arg.Verse,
		arg.Color,
		arg.Note,
	)
	var i BibleHighlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TranslationID,
		&i.Book,
		&i.Chapter,
		&i.Verse,
		&i.Color,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :exec
INSERT INTO reading_progress (user_id, translation_id, book, chapter, last_read_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id, translation_id, book) DO UPDATE SET
    chapter      = EXCLUDED.chapter,
    last_read_at = NOW()
`

type UpsertReadingProgressParams struct {
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	TranslationID int64     `db:"translation_id" json:"translation_id"`
	Book          string    `db:"book" json:"book"`
	Chapter       int32     `db:"chapter" json:"chapter"`
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) error {
	_, err := q.db.Exec(ctx, upsertReadingProgress,
		arg.UserID,
		arg.TranslationID,
		arg.Book,
		arg.Chapter,
	)
	return err
}

const upsertTranslation = `-- name: UpsertTranslation :one
INSERT INTO bible_translations (code, short_name, name, language)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE SET
    short_name = EXCLUDED.short_name,
    name       = EXCLUDED.name,
    language   = EXCLUDED.language
RETURNING id, code, short_name, name, language, created_at
`

type UpsertTranslationParams struct {
	Code      string  `db:"code" json:"code"`
	ShortName *string `db:"short_name" json:"short_name"`
	Name      string  `db:"name" json:"name"`
	Language  string  `db:"language" json:"language"`
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (BibleTranslation, error) {
	row := q.db.QueryRow(ctx, upsertTranslation,
		arg.Code,
		arg.ShortName,
		arg.Name,
		arg.Language,
	)
	var i BibleTranslation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShortName,
		&i.Name,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}
