// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO post_reactions (post_id, user_id, reaction_type)
VALUES ($1, $2, $3)
ON CONFLICT (post_id, user_id, reaction_type) DO NOTHING
`

type AddReactionParams struct {
	PostID       uuid.UUID `db:"post_id" json:"post_id"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	ReactionType string    `db:"reaction_type" json:"reaction_type"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction, arg.PostID, arg.UserID, arg.ReactionType)
	return err
}

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (group_id, creator_id, title, description, type, target, unit, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, creator_id, title, description, type, target, unit, start_date, end_date, created_at
`

type CreateChallengeParams struct {
	GroupID     pgtype.UUID `db:"group_id" json:"group_id"`
	CreatorID   uuid.UUID   `db:"creator_id" json:"creator_id"`
	Title       string      `db:"title" json:"title"`
	Description *string     `db:"description" json:"description"`
	Type        string      `db:"type" json:"type"`
	Target      int32       `db:"target" json:"target"`
	Unit        string      `db:"unit" json:"unit"`
	StartDate   pgtype.Date `db:"start_date" json:"start_date"`
	EndDate     pgtype.Date `db:"end_date" json:"end_date"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.GroupID,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Target,
		arg.Unit,
		arg.StartDate,
		arg.EndDate,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Target,
		&i.Unit,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO post_comments (post_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, post_id, user_id, content, created_at
`

type CreateCommentParams struct {
	PostID  uuid.UUID `db:"post_id" json:"post_id"`
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	Content string    `db:"content" json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (PostComment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.UserID, arg.Content)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, creator_id, is_private, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, creator_id, is_private, avatar_url, created_at
`

type CreateGroupParams struct {
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	CreatorID   uuid.UUID `db:"creator_id" json:"creator_id"`
	IsPrivate   bool      `db:"is_private" json:"is_private"`
	AvatarUrl   *string   `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.CreatorID,
		arg.IsPrivate,
		arg.AvatarUrl,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorID,
		&i.IsPrivate,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, group_id, post_type, content, verse_ref, verse_text)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, group_id, post_type, content, verse_ref, verse_text, created_at, updated_at
`

type CreatePostParams struct {
	UserID    uuid.UUID   `db:"user_id" json:"user_id"`
	GroupID   pgtype.UUID `db:"group_id" json:"group_id"`
	PostType  string      `db:"post_type" json:"post_type"`
	Content   string      `db:"content" json:"content"`
	VerseRef  *string     `db:"verse_ref" json:"verse_ref"`
	VerseText *string     `db:"verse_text" json:"verse_text"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.GroupID,
		arg.PostType,
		arg.Content,
		arg.VerseRef,
		arg.VerseText,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.PostType,
		&i.Content,
		&i.VerseRef,
		&i.VerseText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM post_comments WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.UserID)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, creator_id, is_private, avatar_url, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorID,
		&i.IsPrivate,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT p.id, p.user_id, p.group_id, p.post_type, p.content, p.verse_ref, p.verse_text, p.created_at, p.updated_at, u.name AS author_name, u.avatar_url AS author_avatar
FROM posts p
JOIN users u ON u.id = p.user_id
WHERE p.id = $1
`

type GetPostByIDRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	PostType     string             `db:"post_type" json:"post_type"`
	Content      string             `db:"content" json:"content"`
	VerseRef     *string            `db:"verse_ref" json:"verse_ref"`
	VerseText    *string            `db:"verse_text" json:"verse_text"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorName   string             `db:"author_name" json:"author_name"`
	AuthorAvatar *string            `db:"author_avatar" json:"author_avatar"`
}

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.PostType,
		&i.Content,
		&i.VerseRef,
		&i.VerseText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const getReactionsByPost = `-- name: GetReactionsByPost :many
SELECT reaction_type, COUNT(*) AS count
FROM post_reactions
WHERE post_id = $1
GROUP BY reaction_type
`

type GetReactionsByPostRow struct {
	ReactionType string `db:"reaction_type" json:"reaction_type"`
	Count        int64  `db:"count" json:"count"`
}

func (q *Queries) GetReactionsByPost(ctx context.Context, postID uuid.UUID) ([]GetReactionsByPostRow, error) {
	rows, err := q.db.Query(ctx, getReactionsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionsByPostRow{}
	for rows.Next() {
		var i GetReactionsByPostRow
		if err := rows.Scan(&i.ReactionType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS(
    SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2
) AS is_member
`

type IsGroupMemberParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.GroupID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const joinChallenge = `-- name: JoinChallenge :exec
INSERT INTO challenge_participants (challenge_id, user_id)
VALUES ($1, $2)
ON CONFLICT (challenge_id, user_id) DO NOTHING
`

type JoinChallengeParams struct {
	ChallengeID uuid.UUID `db:"challenge_id" json:"challenge_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) JoinChallenge(ctx context.Context, arg JoinChallengeParams) error {
	_, err := q.db.Exec(ctx, joinChallenge, arg.ChallengeID, arg.UserID)
	return err
}

const joinGroup = `-- name: JoinGroup :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, 'member')
ON CONFLICT (group_id, user_id) DO NOTHING
`

type JoinGroupParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) JoinGroup(ctx context.Context, arg JoinGroupParams) error {
	_, err := q.db.Exec(ctx, joinGroup, arg.GroupID, arg.UserID)
	return err
}

const leaveGroup = `-- name: LeaveGroup :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type LeaveGroupParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) LeaveGroup(ctx context.Context, arg LeaveGroupParams) error {
	_, err := q.db.Exec(ctx, leaveGroup, arg.GroupID, arg.UserID)
	return err
}

const listActiveChallenges = `-- name: ListActiveChallenges :many
SELECT c.id, c.group_id, c.creator_id, c.title, c.description, c.type, c.target, c.unit, c.start_date, c.end_date, c.created_at, cp.progress AS my_progress
FROM challenges c
LEFT JOIN challenge_participants cp ON cp.challenge_id = c.id AND cp.user_id = $1
WHERE c.end_date >= CURRENT_DATE
  AND (c.group_id IS NULL OR c.group_id IN (
      SELECT group_id FROM group_members WHERE user_id = $1
  ))
ORDER BY c.start_date DESC
LIMIT 20
`

type ListActiveChallengesRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	GroupID     pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatorID   uuid.UUID          `db:"creator_id" json:"creator_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Type        string             `db:"type" json:"type"`
	Target      int32              `db:"target" json:"target"`
	Unit        string             `db:"unit" json:"unit"`
	StartDate   pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate     pgtype.Date        `db:"end_date" json:"end_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MyProgress  *int32             `db:"my_progress" json:"my_progress"`
}

func (q *Queries) ListActiveChallenges(ctx context.Context, userID uuid.UUID) ([]ListActiveChallengesRow, error) {
	rows, err := q.db.Query(ctx, listActiveChallenges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveChallengesRow{}
	for rows.Next() {
		var i ListActiveChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Target,
			&i.Unit,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.MyProgress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT pc.id, pc.post_id, pc.user_id, pc.content, pc.created_at, u.name AS author_name, u.avatar_url AS author_avatar
FROM post_comments pc
JOIN users u ON u.id = pc.user_id
WHERE pc.post_id = $1
ORDER BY pc.created_at ASC
`

type ListCommentsRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	PostID       uuid.UUID          `db:"post_id" json:"post_id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AuthorName   string             `db:"author_name" json:"author_name"`
	AuthorAvatar *string            `db:"author_avatar" json:"author_avatar"`
}

func (q *Queries) ListComments(ctx context.Context, postID uuid.UUID) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedPosts = `-- name: ListFeedPosts :many
SELECT p.id, p.user_id, p.group_id, p.post_type, p.content, p.verse_ref, p.verse_text, p.created_at, p.updated_at, u.name AS author_name, u.avatar_url AS author_avatar,
    (SELECT COUNT(*) FROM post_reactions pr WHERE pr.post_id = p.id AND pr.reaction_type = 'amen')    AS amen_count,
    (SELECT COUNT(*) FROM post_reactions pr WHERE pr.post_id = p.id AND pr.reaction_type = 'praying') AS praying_count,
    (SELECT COUNT(*) FROM post_comments pc WHERE pc.post_id = p.id) AS comment_count
FROM posts p
JOIN users u ON u.id = p.user_id
WHERE ($1::uuid IS NULL OR p.group_id = $1)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFeedPostsParams struct {
	Column1 uuid.UUID `db:"column_1" json:"column_1"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

type ListFeedPostsRow struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	PostType     string             `db:"post_type" json:"post_type"`
	Content      string             `db:"content" json:"content"`
	VerseRef     *string            `db:"verse_ref" json:"verse_ref"`
	VerseText    *string            `db:"verse_text" json:"verse_text"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AuthorName   string             `db:"author_name" json:"author_name"`
	AuthorAvatar *string            `db:"author_avatar" json:"author_avatar"`
	AmenCount    int64              `db:"amen_count" json:"amen_count"`
	PrayingCount int64              `db:"praying_count" json:"praying_count"`
	CommentCount int64              `db:"comment_count" json:"comment_count"`
}

func (q *Queries) ListFeedPosts(ctx context.Context, arg ListFeedPostsParams) ([]ListFeedPostsRow, error) {
	rows, err := q.db.Query(ctx, listFeedPosts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedPostsRow{}
	for rows.Next() {
		var i ListFeedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.PostType,
			&i.Content,
			&i.VerseRef,
			&i.VerseText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AmenCount,
			&i.PrayingCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.description, g.creator_id, g.is_private, g.avatar_url, g.created_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY gm.joined_at DESC
`

func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatorID,
			&i.IsPrivate,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM post_reactions
WHERE post_id = $1 AND user_id = $2 AND reaction_type = $3
`

type RemoveReactionParams struct {
	PostID       uuid.UUID `db:"post_id" json:"post_id"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	ReactionType string    `db:"reaction_type" json:"reaction_type"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.PostID, arg.UserID, arg.ReactionType)
	return err
}

const updateChallengeProgress = `-- name: UpdateChallengeProgress :one
INSERT INTO challenge_participants (challenge_id, user_id, progress, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (challenge_id, user_id) DO UPDATE SET
    progress   = EXCLUDED.progress,
    updated_at = NOW()
RETURNING challenge_id, user_id, progress, joined_at, updated_at
`

type UpdateChallengeProgressParams struct {
	ChallengeID uuid.UUID `db:"challenge_id" json:"challenge_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Progress    int32     `db:"progress" json:"progress"`
}

func (q *Queries) UpdateChallengeProgress(ctx context.Context, arg UpdateChallengeProgressParams) (ChallengeParticipant, error) {
	row := q.db.QueryRow(ctx, updateChallengeProgress, arg.ChallengeID, arg.UserID, arg.Progress)
	var i ChallengeParticipant
	err := row.Scan(
		&i.ChallengeID,
		&i.UserID,
		&i.Progress,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}
