// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fasting.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const addCheckin = `-- name: AddCheckin :one
INSERT INTO fast_checkins (fast_id, user_id, mood, reflection)
VALUES ($1, $2, $3, $4)
RETURNING id, fast_id, user_id, mood, reflection, created_at
`

type AddCheckinParams struct {
	FastID     uuid.UUID `db:"fast_id" json:"fast_id"`
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	Mood       string    `db:"mood" json:"mood"`
	Reflection *string   `db:"reflection" json:"reflection"`
}

func (q *Queries) AddCheckin(ctx context.Context, arg AddCheckinParams) (FastCheckin, error) {
	row := q.db.QueryRow(ctx, addCheckin,
		arg.FastID,
		arg.UserID,
		arg.Mood,
		arg.Reflection,
	)
	var i FastCheckin
	err := row.Scan(
		&i.ID,
		&i.FastID,
		&i.UserID,
		&i.Mood,
		&i.Reflection,
		&i.CreatedAt,
	)
	return i, err
}

const endFast = `-- name: EndFast :one
UPDATE fasts SET ended_at = NOW()
WHERE id = $1 AND user_id = $2 AND ended_at IS NULL
RETURNING id, user_id, target_hours, started_at, ended_at, shared, created_at
`

type EndFastParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) EndFast(ctx context.Context, arg EndFastParams) (Fast, error) {
	row := q.db.QueryRow(ctx, endFast, arg.ID, arg.UserID)
	var i Fast
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetHours,
		&i.StartedAt,
		&i.EndedAt,
		&i.Shared,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveFast = `-- name: GetActiveFast :one
SELECT id, user_id, target_hours, started_at, ended_at, shared, created_at FROM fasts
WHERE user_id = $1 AND ended_at IS NULL
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveFast(ctx context.Context, userID uuid.UUID) (Fast, error) {
	row := q.db.QueryRow(ctx, getActiveFast, userID)
	var i Fast
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetHours,
		&i.StartedAt,
		&i.EndedAt,
		&i.Shared,
		&i.CreatedAt,
	)
	return i, err
}

const getFastByID = `-- name: GetFastByID :one
SELECT id, user_id, target_hours, started_at, ended_at, shared, created_at FROM fasts WHERE id = $1 AND user_id = $2
`

type GetFastByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetFastByID(ctx context.Context, arg GetFastByIDParams) (Fast, error) {
	row := q.db.QueryRow(ctx, getFastByID, arg.ID, arg.UserID)
	var i Fast
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetHours,
		&i.StartedAt,
		&i.EndedAt,
		&i.Shared,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCheckin = `-- name: GetLatestCheckin :one
SELECT id, fast_id, user_id, mood, reflection, created_at FROM fast_checkins
WHERE fast_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCheckin(ctx context.Context, fastID uuid.UUID) (FastCheckin, error) {
	row := q.db.QueryRow(ctx, getLatestCheckin, fastID)
	var i FastCheckin
	err := row.Scan(
		&i.ID,
		&i.FastID,
		&i.UserID,
		&i.Mood,
		&i.Reflection,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckins = `-- name: ListCheckins :many
SELECT id, fast_id, user_id, mood, reflection, created_at FROM fast_checkins
WHERE fast_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCheckins(ctx context.Context, fastID uuid.UUID) ([]FastCheckin, error) {
	rows, err := q.db.Query(ctx, listCheckins, fastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FastCheckin{}
	for rows.Next() {
		var i FastCheckin
		if err := rows.Scan(
			&i.ID,
			&i.FastID,
			&i.UserID,
			&i.Mood,
			&i.Reflection,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFasts = `-- name: ListFasts :many
SELECT id, user_id, target_hours, started_at, ended_at, shared, created_at FROM fasts
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListFastsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListFasts(ctx context.Context, arg ListFastsParams) ([]Fast, error) {
	rows, err := q.db.Query(ctx, listFasts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fast{}
	for rows.Next() {
		var i Fast
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetHours,
			&i.StartedAt,
			&i.EndedAt,
			&i.Shared,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startFast = `-- name: StartFast :one
INSERT INTO fasts (user_id, target_hours, started_at)
VALUES ($1, $2, NOW())
RETURNING id, user_id, target_hours, started_at, ended_at, shared, created_at
`

type StartFastParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	TargetHours float64   `db:"target_hours" json:"target_hours"`
}

func (q *Queries) StartFast(ctx context.Context, arg StartFastParams) (Fast, error) {
	row := q.db.QueryRow(ctx, startFast, arg.UserID, arg.TargetHours)
	var i Fast
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetHours,
		&i.StartedAt,
		&i.EndedAt,
		&i.Shared,
		&i.CreatedAt,
	)
	return i, err
}
