// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BibleBookmark struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	TranslationID int64              `db:"translation_id" json:"translation_id"`
	Book          string             `db:"book" json:"book"`
	Chapter       int32              `db:"chapter" json:"chapter"`
	Verse         int32              `db:"verse" json:"verse"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BibleDailyCache struct {
	CacheDate     pgtype.Date `db:"cache_date" json:"cache_date"`
	TranslationID int64       `db:"translation_id" json:"translation_id"`
	Book          string      `db:"book" json:"book"`
	Chapter       int32       `db:"chapter" json:"chapter"`
	Verse         int32       `db:"verse" json:"verse"`
}

type BibleHighlight struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	TranslationID int64              `db:"translation_id" json:"translation_id"`
	Book          string             `db:"book" json:"book"`
	Chapter       int32              `db:"chapter" json:"chapter"`
	Verse         int32              `db:"verse" json:"verse"`
	Color         string             `db:"color" json:"color"`
	Note          *string            `db:"note" json:"note"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BibleTranslation struct {
	ID        int64              `db:"id" json:"id"`
	Code      string             `db:"code" json:"code"`
	ShortName *string            `db:"short_name" json:"short_name"`
	Name      string             `db:"name" json:"name"`
	Language  string             `db:"language" json:"language"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BibleVerse struct {
	ID            int64  `db:"id" json:"id"`
	TranslationID int64  `db:"translation_id" json:"translation_id"`
	Book          string `db:"book" json:"book"`
	Chapter       int32  `db:"chapter" json:"chapter"`
	Verse         int32  `db:"verse" json:"verse"`
	Text          string `db:"text" json:"text"`
}

type Challenge struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	GroupID     pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatorID   uuid.UUID          `db:"creator_id" json:"creator_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Type        string             `db:"type" json:"type"`
	Target      int32              `db:"target" json:"target"`
	Unit        string             `db:"unit" json:"unit"`
	StartDate   pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate     pgtype.Date        `db:"end_date" json:"end_date"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ChallengeParticipant struct {
	ChallengeID uuid.UUID          `db:"challenge_id" json:"challenge_id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Progress    int32              `db:"progress" json:"progress"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Fast struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	TargetHours float64            `db:"target_hours" json:"target_hours"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt     pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	Shared      bool               `db:"shared" json:"shared"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type FastCheckin struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	FastID     uuid.UUID          `db:"fast_id" json:"fast_id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Mood       string             `db:"mood" json:"mood"`
	Reflection *string            `db:"reflection" json:"reflection"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Friendship struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	FriendID  uuid.UUID          `db:"friend_id" json:"friend_id"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Group struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	CreatorID   uuid.UUID          `db:"creator_id" json:"creator_id"`
	IsPrivate   bool               `db:"is_private" json:"is_private"`
	AvatarUrl   *string            `db:"avatar_url" json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GroupMember struct {
	GroupID  uuid.UUID          `db:"group_id" json:"group_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type MeditationSession struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	Title           string             `db:"title" json:"title"`
	SessionType     string             `db:"session_type" json:"session_type"`
	DurationSeconds int32              `db:"duration_seconds" json:"duration_seconds"`
	Completed       bool               `db:"completed" json:"completed"`
	VerseBook       *string            `db:"verse_book" json:"verse_book"`
	VerseChapter    *int32             `db:"verse_chapter" json:"verse_chapter"`
	VerseNumber     *int32             `db:"verse_number" json:"verse_number"`
	VerseText       *string            `db:"verse_text" json:"verse_text"`
	VerseRef        *string            `db:"verse_ref" json:"verse_ref"`
	Note            *string            `db:"note" json:"note"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type Milestone struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	Type     string             `db:"type" json:"type"`
	Label    string             `db:"label" json:"label"`
	EarnedAt pgtype.Timestamptz `db:"earned_at" json:"earned_at"`
}

type Post struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	GroupID   pgtype.UUID        `db:"group_id" json:"group_id"`
	PostType  string             `db:"post_type" json:"post_type"`
	Content   string             `db:"content" json:"content"`
	VerseRef  *string            `db:"verse_ref" json:"verse_ref"`
	VerseText *string            `db:"verse_text" json:"verse_text"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PostComment struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	PostID    uuid.UUID          `db:"post_id" json:"post_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Content   string             `db:"content" json:"content"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PostReaction struct {
	PostID       uuid.UUID          `db:"post_id" json:"post_id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	ReactionType string             `db:"reaction_type" json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ReadingProgress struct {
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	TranslationID int64              `db:"translation_id" json:"translation_id"`
	Book          string             `db:"book" json:"book"`
	Chapter       int32              `db:"chapter" json:"chapter"`
	LastReadAt    pgtype.Timestamptz `db:"last_read_at" json:"last_read_at"`
}

type Session struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	IpAddress *string            `db:"ip_address" json:"ip_address"`
	UserAgent *string            `db:"user_agent" json:"user_agent"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SpiritualGoal struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	GoalType  string             `db:"goal_type" json:"goal_type"`
	Target    int32              `db:"target" json:"target"`
	Unit      string             `db:"unit" json:"unit"`
	Frequency string             `db:"frequency" json:"frequency"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Streak struct {
	UserID           uuid.UUID   `db:"user_id" json:"user_id"`
	ActivityType     string      `db:"activity_type" json:"activity_type"`
	CurrentStreak    int32       `db:"current_streak" json:"current_streak"`
	LongestStreak    int32       `db:"longest_streak" json:"longest_streak"`
	LastActivityDate pgtype.Date `db:"last_activity_date" json:"last_activity_date"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         *string            `db:"email" json:"email"`
	Name          string             `db:"name" json:"name"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	Bio           *string            `db:"bio" json:"bio"`
	Level         int32              `db:"level" json:"level"`
	Xp            int32              `db:"xp" json:"xp"`
	Visibility    string             `db:"visibility" json:"visibility"`
	GoogleSub     *string            `db:"google_sub" json:"google_sub"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserCredential struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserReminder struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Type      string             `db:"type" json:"type"`
	TimeHhmm  string             `db:"time_hhmm" json:"time_hhmm"`
	Enabled   bool               `db:"enabled" json:"enabled"`
	Label     *string            `db:"label" json:"label"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
