// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeMeditationSession = `-- name: CompleteMeditationSession :one
UPDATE meditation_sessions SET
    completed    = TRUE,
    note         = COALESCE($2, note),
    completed_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, title, session_type, duration_seconds, completed, verse_book, verse_chapter, verse_number, verse_text, verse_ref, note, started_at, completed_at
`

type CompleteMeditationSessionParams struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	Note   *string     `db:"note" json:"note"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CompleteMeditationSession(ctx context.Context, arg CompleteMeditationSessionParams) (MeditationSession, error) {
	row := q.db.QueryRow(ctx, completeMeditationSession, arg.ID, arg.Note, arg.UserID)
	var i MeditationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SessionType,
		&i.DurationSeconds,
		&i.Completed,
		&i.VerseBook,
		&i.VerseChapter,
		&i.VerseNumber,
		&i.VerseText,
		&i.VerseRef,
		&i.Note,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCompletedSessionsOnDate = `-- name: CountCompletedSessionsOnDate :one
SELECT COUNT(*) FROM meditation_sessions
WHERE user_id = $1
  AND completed = TRUE
  AND DATE(completed_at) = $2::date
`

type CountCompletedSessionsOnDateParams struct {
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Column2 pgtype.Date `db:"column_2" json:"column_2"`
}

func (q *Queries) CountCompletedSessionsOnDate(ctx context.Context, arg CountCompletedSessionsOnDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedSessionsOnDate, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMeditationSession = `-- name: CreateMeditationSession :one
INSERT INTO meditation_sessions (
    user_id, title, session_type, duration_seconds,
    verse_book, verse_chapter, verse_number, verse_text, verse_ref
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, title, session_type, duration_seconds, completed, verse_book, verse_chapter, verse_number, verse_text, verse_ref, note, started_at, completed_at
`

type CreateMeditationSessionParams struct {
	UserID          pgtype.UUID `db:"user_id" json:"user_id"`
	Title           string      `db:"title" json:"title"`
	SessionType     string      `db:"session_type" json:"session_type"`
	DurationSeconds int32       `db:"duration_seconds" json:"duration_seconds"`
	VerseBook       *string     `db:"verse_book" json:"verse_book"`
	VerseChapter    *int32      `db:"verse_chapter" json:"verse_chapter"`
	VerseNumber     *int32      `db:"verse_number" json:"verse_number"`
	VerseText       *string     `db:"verse_text" json:"verse_text"`
	VerseRef        *string     `db:"verse_ref" json:"verse_ref"`
}

func (q *Queries) CreateMeditationSession(ctx context.Context, arg CreateMeditationSessionParams) (MeditationSession, error) {
	row := q.db.QueryRow(ctx, createMeditationSession,
		arg.UserID,
		arg.Title,
		arg.SessionType,
		arg.DurationSeconds,
		arg.VerseBook,
		arg.VerseChapter,
		arg.VerseNumber,
		arg.VerseText,
		arg.VerseRef,
	)
	var i MeditationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SessionType,
		&i.DurationSeconds,
		&i.Completed,
		&i.VerseBook,
		&i.VerseChapter,
		&i.VerseNumber,
		&i.VerseText,
		&i.VerseRef,
		&i.Note,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMeditationSession = `-- name: GetMeditationSession :one
SELECT id, user_id, title, session_type, duration_seconds, completed, verse_book, verse_chapter, verse_number, verse_text, verse_ref, note, started_at, completed_at FROM meditation_sessions WHERE id = $1 AND user_id = $2
`

type GetMeditationSessionParams struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMeditationSession(ctx context.Context, arg GetMeditationSessionParams) (MeditationSession, error) {
	row := q.db.QueryRow(ctx, getMeditationSession, arg.ID, arg.UserID)
	var i MeditationSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SessionType,
		&i.DurationSeconds,
		&i.Completed,
		&i.VerseBook,
		&i.VerseChapter,
		&i.VerseNumber,
		&i.VerseText,
		&i.VerseRef,
		&i.Note,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listMeditationSessions = `-- name: ListMeditationSessions :many
SELECT id, user_id, title, session_type, duration_seconds, completed, verse_book, verse_chapter, verse_number, verse_text, verse_ref, note, started_at, completed_at FROM meditation_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListMeditationSessionsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListMeditationSessions(ctx context.Context, arg ListMeditationSessionsParams) ([]MeditationSession, error) {
	rows, err := q.db.Query(ctx, listMeditationSessions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeditationSession{}
	for rows.Next() {
		var i MeditationSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.SessionType,
			&i.DurationSeconds,
			&i.Completed,
			&i.VerseBook,
			&i.VerseChapter,
			&i.VerseNumber,
			&i.VerseText,
			&i.VerseRef,
			&i.Note,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
