// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const awardMilestone = `-- name: AwardMilestone :one
INSERT INTO milestones (user_id, type, label)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, type) DO NOTHING
RETURNING id, user_id, type, label, earned_at
`

type AwardMilestoneParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Type   string    `db:"type" json:"type"`
	Label  string    `db:"label" json:"label"`
}

func (q *Queries) AwardMilestone(ctx context.Context, arg AwardMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, awardMilestone, arg.UserID, arg.Type, arg.Label)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.EarnedAt,
	)
	return i, err
}

const getConsistencyMap = `-- name: GetConsistencyMap :many
SELECT DISTINCT DATE(started_at) AS active_date
FROM meditation_sessions
WHERE user_id = $1
  AND completed = TRUE
  AND started_at >= $2::timestamptz
  AND started_at < $3::timestamptz
ORDER BY active_date
`

type GetConsistencyMapParams struct {
	UserID  pgtype.UUID        `db:"user_id" json:"user_id"`
	Column2 pgtype.Timestamptz `db:"column_2" json:"column_2"`
	Column3 pgtype.Timestamptz `db:"column_3" json:"column_3"`
}

func (q *Queries) GetConsistencyMap(ctx context.Context, arg GetConsistencyMapParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, getConsistencyMap, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var active_date pgtype.Date
		if err := rows.Scan(&active_date); err != nil {
			return nil, err
		}
		items = append(items, active_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMilestones = `-- name: GetMilestones :many
SELECT id, user_id, type, label, earned_at FROM milestones WHERE user_id = $1 ORDER BY earned_at DESC
`

func (q *Queries) GetMilestones(ctx context.Context, userID uuid.UUID) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, getMilestones, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Label,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreakByType = `-- name: GetStreakByType :one
SELECT user_id, activity_type, current_streak, longest_streak, last_activity_date FROM streaks WHERE user_id = $1 AND activity_type = $2
`

type GetStreakByTypeParams struct {
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	ActivityType string    `db:"activity_type" json:"activity_type"`
}

func (q *Queries) GetStreakByType(ctx context.Context, arg GetStreakByTypeParams) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreakByType, arg.UserID, arg.ActivityType)
	var i Streak
	err := row.Scan(
		&i.UserID,
		&i.ActivityType,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
	)
	return i, err
}

const getStreaks = `-- name: GetStreaks :many
SELECT user_id, activity_type, current_streak, longest_streak, last_activity_date FROM streaks WHERE user_id = $1
`

func (q *Queries) GetStreaks(ctx context.Context, userID uuid.UUID) ([]Streak, error) {
	rows, err := q.db.Query(ctx, getStreaks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Streak{}
	for rows.Next() {
		var i Streak
		if err := rows.Scan(
			&i.UserID,
			&i.ActivityType,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.LastActivityDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklySessionMinutes = `-- name: GetWeeklySessionMinutes :many
SELECT
    DATE(started_at) AS day,
    SUM(duration_seconds) / 60 AS minutes
FROM meditation_sessions
WHERE user_id = $1
  AND completed = TRUE
  AND started_at >= NOW() - INTERVAL '7 days'
GROUP BY DATE(started_at)
ORDER BY day
`

type GetWeeklySessionMinutesRow struct {
	Day     pgtype.Date `db:"day" json:"day"`
	Minutes int32       `db:"minutes" json:"minutes"`
}

func (q *Queries) GetWeeklySessionMinutes(ctx context.Context, userID pgtype.UUID) ([]GetWeeklySessionMinutesRow, error) {
	rows, err := q.db.Query(ctx, getWeeklySessionMinutes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeeklySessionMinutesRow{}
	for rows.Next() {
		var i GetWeeklySessionMinutesRow
		if err := rows.Scan(&i.Day, &i.Minutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStreak = `-- name: UpsertStreak :one
INSERT INTO streaks (user_id, activity_type, current_streak, longest_streak, last_activity_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, activity_type) DO UPDATE SET
    current_streak     = EXCLUDED.current_streak,
    longest_streak     = GREATEST(streaks.longest_streak, EXCLUDED.longest_streak),
    last_activity_date = EXCLUDED.last_activity_date
RETURNING user_id, activity_type, current_streak, longest_streak, last_activity_date
`

type UpsertStreakParams struct {
	UserID           uuid.UUID   `db:"user_id" json:"user_id"`
	ActivityType     string      `db:"activity_type" json:"activity_type"`
	CurrentStreak    int32       `db:"current_streak" json:"current_streak"`
	LongestStreak    int32       `db:"longest_streak" json:"longest_streak"`
	LastActivityDate pgtype.Date `db:"last_activity_date" json:"last_activity_date"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, upsertStreak,
		arg.UserID,
		arg.ActivityType,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastActivityDate,
	)
	var i Streak
	err := row.Scan(
		&i.UserID,
		&i.ActivityType,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
	)
	return i, err
}
