// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addXP = `-- name: AddXP :one
UPDATE users SET
    xp    = xp + $2,
    level = GREATEST(1, FLOOR(SQRT((xp + $2)::float / 100))::int + 1),
    updated_at = NOW()
WHERE id = $1
RETURNING xp, level
`

type AddXPParams struct {
	ID uuid.UUID `db:"id" json:"id"`
	Xp int32     `db:"xp" json:"xp"`
}

type AddXPRow struct {
	Xp    int32 `db:"xp" json:"xp"`
	Level int32 `db:"level" json:"level"`
}

func (q *Queries) AddXP(ctx context.Context, arg AddXPParams) (AddXPRow, error) {
	row := q.db.QueryRow(ctx, addXP, arg.ID, arg.Xp)
	var i AddXPRow
	err := row.Scan(&i.Xp, &i.Level)
	return i, err
}

const deleteSpiritualGoal = `-- name: DeleteSpiritualGoal :exec
DELETE FROM spiritual_goals WHERE user_id = $1 AND goal_type = $2
`

type DeleteSpiritualGoalParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	GoalType string    `db:"goal_type" json:"goal_type"`
}

func (q *Queries) DeleteSpiritualGoal(ctx context.Context, arg DeleteSpiritualGoalParams) error {
	_, err := q.db.Exec(ctx, deleteSpiritualGoal, arg.UserID, arg.GoalType)
	return err
}

const getFriendships = `-- name: GetFriendships :many
SELECT f.friend_id, u.name, u.avatar_url, u.level, f.status, f.created_at
FROM friendships f
JOIN users u ON u.id = f.friend_id
WHERE f.user_id = $1 AND f.status = 'accepted'
`

type GetFriendshipsRow struct {
	FriendID  uuid.UUID          `db:"friend_id" json:"friend_id"`
	Name      string             `db:"name" json:"name"`
	AvatarUrl *string            `db:"avatar_url" json:"avatar_url"`
	Level     int32              `db:"level" json:"level"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetFriendships(ctx context.Context, userID uuid.UUID) ([]GetFriendshipsRow, error) {
	rows, err := q.db.Query(ctx, getFriendships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFriendshipsRow{}
	for rows.Next() {
		var i GetFriendshipsRow
		if err := rows.Scan(
			&i.FriendID,
			&i.Name,
			&i.AvatarUrl,
			&i.Level,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReminders = `-- name: GetReminders :many
SELECT id, user_id, type, time_hhmm, enabled, label, created_at, updated_at FROM user_reminders WHERE user_id = $1
`

func (q *Queries) GetReminders(ctx context.Context, userID uuid.UUID) ([]UserReminder, error) {
	rows, err := q.db.Query(ctx, getReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserReminder{}
	for rows.Next() {
		var i UserReminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.TimeHhmm,
			&i.Enabled,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpiritualGoals = `-- name: GetSpiritualGoals :many
SELECT id, user_id, goal_type, target, unit, frequency, created_at, updated_at FROM spiritual_goals WHERE user_id = $1
`

func (q *Queries) GetSpiritualGoals(ctx context.Context, userID uuid.UUID) ([]SpiritualGoal, error) {
	rows, err := q.db.Query(ctx, getSpiritualGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpiritualGoal{}
	for rows.Next() {
		var i SpiritualGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoalType,
			&i.Target,
			&i.Unit,
			&i.Frequency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondFriendRequest = `-- name: RespondFriendRequest :exec
UPDATE friendships SET status = $3
WHERE user_id = $1 AND friend_id = $2
`

type RespondFriendRequestParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	FriendID uuid.UUID `db:"friend_id" json:"friend_id"`
	Status   string    `db:"status" json:"status"`
}

func (q *Queries) RespondFriendRequest(ctx context.Context, arg RespondFriendRequestParams) error {
	_, err := q.db.Exec(ctx, respondFriendRequest, arg.UserID, arg.FriendID, arg.Status)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, avatar_url, level
FROM users
WHERE name ILIKE '%' || $1 || '%'
  AND visibility != 'private'
LIMIT 20
`

type SearchUsersRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	AvatarUrl *string   `db:"avatar_url" json:"avatar_url"`
	Level     int32     `db:"level" json:"level"`
}

func (q *Queries) SearchUsers(ctx context.Context, dollar_1 *string) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvatarUrl,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendFriendRequest = `-- name: SendFriendRequest :exec
INSERT INTO friendships (user_id, friend_id, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (user_id, friend_id) DO NOTHING
`

type SendFriendRequestParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	FriendID uuid.UUID `db:"friend_id" json:"friend_id"`
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) error {
	_, err := q.db.Exec(ctx, sendFriendRequest, arg.UserID, arg.FriendID)
	return err
}

const upsertReminder = `-- name: UpsertReminder :one
INSERT INTO user_reminders (user_id, type, time_hhmm, enabled, label)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, type) DO UPDATE SET
    time_hhmm  = EXCLUDED.time_hhmm,
    enabled    = EXCLUDED.enabled,
    label      = EXCLUDED.label,
    updated_at = NOW()
RETURNING id, user_id, type, time_hhmm, enabled, label, created_at, updated_at
`

type UpsertReminderParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Type     string    `db:"type" json:"type"`
	TimeHhmm string    `db:"time_hhmm" json:"time_hhmm"`
	Enabled  bool      `db:"enabled" json:"enabled"`
	Label    *string   `db:"label" json:"label"`
}

func (q *Queries) UpsertReminder(ctx context.Context, arg UpsertReminderParams) (UserReminder, error) {
	row := q.db.QueryRow(ctx, upsertReminder,
		arg.UserID,
		arg.Type,
		arg.TimeHhmm,
		arg.Enabled,
		arg.Label,
	)
	var i UserReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.TimeHhmm,
		&i.Enabled,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpiritualGoal = `-- name: UpsertSpiritualGoal :one
INSERT INTO spiritual_goals (user_id, goal_type, target, unit, frequency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, goal_type) DO UPDATE SET
    target     = EXCLUDED.target,
    unit       = EXCLUDED.unit,
    frequency  = EXCLUDED.frequency,
    updated_at = NOW()
RETURNING id, user_id, goal_type, target, unit, frequency, created_at, updated_at
`

type UpsertSpiritualGoalParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	GoalType  string    `db:"goal_type" json:"goal_type"`
	Target    int32     `db:"target" json:"target"`
	Unit      string    `db:"unit" json:"unit"`
	Frequency string    `db:"frequency" json:"frequency"`
}

func (q *Queries) UpsertSpiritualGoal(ctx context.Context, arg UpsertSpiritualGoalParams) (SpiritualGoal, error) {
	row := q.db.QueryRow(ctx, upsertSpiritualGoal,
		arg.UserID,
		arg.GoalType,
		arg.Target,
		arg.Unit,
		arg.Frequency,
	)
	var i SpiritualGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoalType,
		&i.Target,
		&i.Unit,
		&i.Frequency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
